### ISSUE TITLE
why are there some extra artifacts in the reconstruction result.

### ISSUE THREAD

**Issue by marrblue** [PRBonn/SHINE_mapping#12]
Great job I must to say first.
Here I just found some strange results in my tests as shown in the screen shot.
I used shine_batch.py to rebuild maicity model, leaf voxel size, mc_res was set to 0.2m, 0.1m respectively. iters = 20000.
Other parameters keep defaults basically.
It seems like there's an extra part of the final result. I am wondering if you have any clues and ideas for this.
<img width="864" alt="image" src="https://user-images.githubusercontent.com/31070287/225562742-106d78e0-f65b-422c-9141-f6253db9ca1a.png">
<img width="411" alt="image" src="https://user-images.githubusercontent.com/31070287/225563164-7991f20f-9d79-40c5-8adf-352bb76ba01c.png">
The distance between the "false wall" and the real wall is about 30cm
I noticed that you have updated the code. This result is produced by the old version code.

**Comment by StarryN** [comment]
Hello @marrblue, Thanks for your interest in our work.
The reason is that we have no real observation behind the wall, and under the current mechanism, the not observed area will be regarded as free (SDF > 0) by default. But behind the wall, a small area is labeled as occupied (SDF < 0) because of our sampling strategy, then the 0 level-set boundaries appeared.
In the old version code, we calculate SDF uniformly in the whole space but only extract mesh from the octree leaf node. In this way, we can avoid extracting most of the fake wall. And in the current version, we only calculate SDF in the leaf nodes to remove even more fake walls than the old one.
I hope I have answered your question.

**Comment by marrblue** [comment]
Hi @StarryN !  your answer is very reasonable and I will try to avoid this problem by modifying related codes. Thank you!
