### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by whwh747** [PRBonn/SHINE_mapping#37]
Thank you for your excellent work. I used kiss icp + python shine_batch.py config/maicity/maicity_batch.yaml and got some strange results. What could be the reason for this?
![84781ce4bcf099b386576ace48fd340](https://github.com/user-attachments/assets/5c6ea8e7-393f-44c5-aee1-8b3e454cb64d)

**Comment by YuePanEdward** [comment]
Hi, I guess the reason is that the pose estimated by KISS-ICP on this sequence using the default parameter is not correct.

![shine_issue37](https://github.com/user-attachments/assets/4f1cb495-fd99-4289-8973-a1804257cf6f)

As I also mentioned in this issue https://github.com/PRBonn/PIN_SLAM/issues/28, the simulation of the poses in MaiCity does not obey the common kinematics of robots. You may check here for more details: https://github.com/PRBonn/kiss-icp/issues/62. Mai-city was not designed to benchmark odometry systems.

**Comment by whwh747** [comment]
thank you，I see, perhaps we can provide the poses obtained from another odometry to SHINE.
